### ISSUE TITLE
Form reset short version

### ISSUE THREAD

**Issue by stephenkati** [HERMON-1995/Book-store-project#6]
https://github.com/HERMON-1995/Book-store/blob/b3640a73a5e48bcbe183f53e1c847f6611804b5b/src/components/addBooks.js#L33-L35 Use this instead ( `document.querySelector('form').reset();` ), its much simpler and does not change when number of form inputs change

**Comment by HERMON-1995** [comment]
Thank you for your suggestion, I will consider using that! 😊
